export const rulingDetails = [
    {
        id: 1,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/atuwatse_iii.jpg",
        name: "Chief Johnson Amatserunleghe",
        title: " The Iyatsere of Warri",
        appellation: " Uji",
    },
    {
        id: 2,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Gabriel Awala",
        title: " The Uwangue of Warri",
        appellation: "Orieku",
    },
    {
        id: 3,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief T.Y. Pessu",
        title: " The Ojomo of Warr",
        appellation: "Utioba",
    },
    {
        id: 4,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Sunday Rone",
        title: " The Obazuaye of Warri",
        appellation: "<b>Ogienoyibo",
    },
    {
        id: 5,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Dr.) P.E.B. Uku",
        title: " The Ere Oluyon of Warri",
        appellation: "Ere-Egwa",
    },
    {
        id: 6,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief G.T. Grant",
        title: " The Agura-Otiri of Warri",
        appellation: "Agbusibiro",
    },
    {
        id: 7,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Mrs.) R. L. Ogbebor",
        title: " The Igba of Warri",
        appellation: "Irojowo",
    },
    {
        id: 8,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Kofi Kartey",
        title: "The Abolujiyan of Warri",
        appellation: "Ebirenegbo",
    },
    {
        id: 9,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Brown Mene",
        title: " The Ogwaolusan of Warri",
        appellation: "Esemuede",
    },
    {
        id: 10,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Elder Walter Odeli (JP)",
        title: " The Oritsegbogwa of Warri",
        appellation: "Oritsetsolatse",
    },
    {
        id: 11,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Sir) E. T. Heymann (KSQ)",
        title: " The Eyeoluyon of Warri",
        appellation: "Adugeneyindolo",
    },
    {
        id: 12,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Dr.) R. L. Oritsejafor",
        title: " The Ogwa of Warri",
        appellation: "Uwa-Eye",
    },
    {
        id: 13,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Felix Esisi",
        title: " The Olare-Aja of Okere",
        appellation: "Ogieboro",
    },
    {
        id: 14,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Sir) P. D. Yalaju (KSQ)",
        title: " The Kenekuniraro of Warri",
        appellation: "Adolo",
    },
    {
        id: 15,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Francis Omatseye",
        title: " The Edigbe of Warri",
        appellation: "Ujatoli",
    },
    {
        id: 16,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Engr. Oma Eyewuoma",
        title: " The Aboludero of Warri",
        appellation: "Oyan",
    },
    {
        id: 17,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Madam) Roli O. Oritsejafor",
        title: " The Iyeolumaete of Warri",
        appellation: "Ogbodu – Iyawa",
    },
    {
        id: 18,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Otimeyin Adams",
        title: " The Aguinode of Warri",
        appellation: "Ojowuro",
    },
    {
        id: 19,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Thomas Ereyitomi",
        title: " The Akatigbi –Ayeola of Warri",
        appellation: "Ojogbojo",
    },
    {
        id: 20,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Richmond O. McGray",
        title: " The Oritseboluwor of Warri",
        appellation: "Ogiaganusi",
    },
    {
        id: 21,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Billy Besigiwa",
        title: " The Osolo of Warri",
        appellation: "Ogboge - Nijebu",
    },
    {
        id: 22,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Eddy Eyitemi Olley",
        title: " The Agbarame (Ofone) of Warri",
        appellation: "Eni",
    },
    {
        id: 23,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Roland A. Omagbemi",
        title: " The Ewolufun of Warri",
        appellation: "Ogban",
    },
    {
        id: 24,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Engr. Anthony Onuwaje",
        title: " The Aboluwo of Warri",
        appellation: "Onogunjegbe",
    },
    {
        id: 25,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Fred Ogbe",
        title: " The Idorsu of Warri",
        appellation: "Eginoghoyo",
    },
    {
        id: 26,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Prest Udueyin",
        title: " The Akwinitsokan of Warri",
        appellation: "Adobodoji",
    },
    {
        id: 27,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Mrs.) Mercy Olowu",
        title: " The UtukpaOritse Erun of Warri",
        appellation: "Eriegwa",
    },
    {
        id: 28,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Eyitemi Arthur Diden",
        title: " The IdeOfene of Warri",
        appellation: "Agboburukunjakan",
    },
    {
        id: 29,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Omolubi Newuwumi",
        title: " The Oma Tamudenyin of Warri",
        appellation: "Egindeghere Ugbo",
    },
    {
        id: 30,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Clement Akpeto Maleghemi",
        title: " The Udefi of Warri",
        appellation: "Obaloye",
    },
    {
        id: 30,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Dr. (Mrs.) Caroline Ajuyah",
        title: " The Olunuranran of Warri",
        appellation: "Iro’lobe",
    },
    {
        id: 31,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Dr. Joseph S. Otumara",
        title: " The Obarisuwa of Warri",
        appellation: "Osuolele",
    },
    {
        id: 32,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Solomon Arenyeka",
        title: " The Eson of Warri",
        appellation: "Otueje",
    },
    {
        id: 33,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Sam Amatotsero",
        title: " The Oluyemi of Warri",
        appellation: "Omotsonighele",
    },
    {
        id: 34,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Francis Maku",
        title: " The Ikenlorire of Warri",
        appellation: " Ijeguen",
    },
    {
        id: 35,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Luck Ereku",
        title: " The AtsetinOlu of Warri",
        appellation: " Ogiesamalele",
    },
    {
        id: 36,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Alex Omaghomi",
        title: " The Imaran of Warri",
        appellation: " Omayoye",
    },
    {
        id: 37,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Mrs.) Winifred Agbejule",
        title: " The Oyeifo of Warri",
        appellation: " Otsowode",
    },
    {
        id: 38,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Mrs.) Patricia Otuedon Arawore",
        title: " The AtsejuOlu of Warri",
        appellation: " Ogifie",
    },
    {
        id: 39,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Prof. Itse Sagay",
        title: " The Olufusi of Warri",
        appellation: " Ogodobiri",

        id: 40,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Tunde Okoturo",
        title: " The Ugo of Warri",
        appellation: " Ugoniwere",
    },
    {
        id: 41,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Leemon Ikpea",
        title: " The Odolagbon of Warri",
        appellation: " Edemayogho",
    },
    {
        id: 42,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Sen. Daisy Danjuma",
        title: " The AguraIwere of Warri",
        appellation: " Ewakpakpa",
    },
    {
        id: 43,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Fred Edegbele",
        title: " The Ikenuwa of Warri",
        appellation: " Orurunagbakiridi",
    },
    {
        id: 44,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Michael Odeli",
        title: " The Olorogun of Warri",
        appellation: " Okolokotuse",
    },
    {
        id: 45,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Akoma Demiyin",
        title: " The Omoku of Warri",
        appellation: " Egbewu",
    },
    {
        id: 46,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Barr. Edward Ekpoko",
        title: " The Tolureju of Warri",
        appellation: " Erebeni",
    },
    {
        id: 47,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Amanoritsewo Atiwa",
        title: " The Otsoron of Warri",
        appellation: " Edegberoko",
    },
    {
        id: 48,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Barr.) Olivia Agbajoh",
        title: " The Oyewumi of Warri",
        appellation: " Egudeghe",
    },
    {
        id: 49,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Barr.) Robinson Ariyo",
        title: " The Egogo Iwere of Warri",
        appellation: " Arayuwa",
    },
    {
        id: 50,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Tony Ede",
        title: " The Uwa Olu Etan of Warri",
        appellation: " Eribonosioba",
    },
    {
        id: 51,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Eugene Ikomi",
        title: " The Olulaye of Warri",
        appellation: " Oghoroju",
    },
    {
        id: 52,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Emmanuel Uduaghan",
        title: " The Alema of Warri",
        appellation: " Agbegherendiden",
    },
    {
        id: 53,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Emmanuel O. Ejutse",
        title: "  The Uranran Ogiame of Warri",
        appellation: " Ekoro-Usin",
    },
    {
        id: 54,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Dr. Mogba Eyeoyibo",
        title: " The Ogholuwarami of Warri",
        appellation: " Otsofu",
    },
    {
        id: 55,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Josephine Onemu",
        title: " The Ogwa Olu Ete of Warri",
        appellation: " Eperugo",
    },
]